language: php

matrix:
  include:
    - php: 7.3
    - php: 7.2
      env: RUN_COVERAGE=1
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      dist: trusty

sudo: false

script: ./build.sh
