name: build and publish

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

env:
  TERM: xterm-256color

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 5.5
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Set RUN_COVERAGE
        run: |
          echo "RUN_COVERAGE=true" >> $GITHUB_ENV
        if: matrix.php-version == '8.1'

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Clover to LCOV
        uses: andstor/clover2lcov-action@v1
        with:
          src: build/clover.xml
          dst: build/lcov.info
        if: matrix.php-version == '8.1'

      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/lcov.info
        if: matrix.php-version == '8.1'
